### ISSUE TITLE
Sinter incompatible with latest stim release

### ISSUE THREAD

**Issue by oscarhiggott** [quantumlib/Stim#256]
Sinter uses some functionality available in the latest dev version of stim that's not yet released on PyPI, so I get the following error when running the first example in the sinter readme:

```
TypeError: sample_write(): incompatible function arguments. The following argument types are supported:
    1. (self: stim._stim_march_sse2.CompiledDetectorSampler, shots: int, *, filepath: str, format: str = '01', prepend_observables: bool = False, append_observables: bool = False) -> None

Invoked with: stim.CompiledDetectorSampler(stim.Circuit('''
    QUBIT_COORDS(1, 1) 1
    QUBIT_COORDS(2, 0) 2
    QUBIT_COORDS(3, 1) 3
    QUBIT_COORDS(5, 1) 5
    QUBIT_COORDS(1, 3) 8
    QUBIT_COORDS(2, 2) 9
    QUBIT_COORDS(3, 3) 10
    QUBIT_COORDS(4, 2) 11
    QUBIT_COORDS(5, 3) 12
    QUBIT_COORDS(6, 2) 13
    QUBIT_COORDS(0, 4) 14
    QUBIT_COORDS(1, 5) 15
    QUBIT_COORDS(2, 4) 16
    QUBIT_COORDS(3, 5) 17
    QUBIT_COORDS(4, 4) 18
    QUBIT_COORDS(5, 5) 19
    QUBIT_COORDS(4, 6) 25
    RX 1 3 5 8 10 12 15 17 19
    R 2 9 11 13 14 16 18 25
    TICK
    H 2 11 16 25
    DEPOLARIZE1(0.001) 2 11 16 25
    TICK
    CX 2 3 16 17 11 12 15 14 10 9 19 18
    DEPOLARIZE2(0.001) 2 3 16 17 11 12 15 14 10 9 19 18
    TICK
    CX 2 1 16 15 11 10 8 14 3 9 12 18
    DEPOLARIZE2(0.001) 2 1 16 15 11 10 8 14 3 9 12 18
    TICK
    CX 16 10 11 5 25 19 8 9 17 18 12 13
    DEPOLARIZE2(0.001) 16 10 11 5 25 19 8 9 17 18 12 13
    TICK
    CX 16 8 11 3 25 17 1 9 10 18 5 13
    DEPOLARIZE2(0.001) 16 8 11 3 25 17 1 9 10 18 5 13
    TICK
    H 2 11 16 25
    DEPOLARIZE1(0.001) 2 11 16 25
    TICK
    MR 2 9 11 13 14 16 18 25
    DETECTOR(2, 0, 0) rec[-8]
    DETECTOR(2, 4, 0) rec[-3]
    DETECTOR(4, 2, 0) rec[-6]
    DETECTOR(4, 6, 0) rec[-1]
    REPEAT 2 {
        TICK
        H 2 11 16 25
        DEPOLARIZE1(0.001) 2 11 16 25
        TICK
        CX 2 3 16 17 11 12 15 14 10 9 19 18
        DEPOLARIZE2(0.001) 2 3 16 17 11 12 15 14 10 9 19 18
        TICK
        CX 2 1 16 15 11 10 8 14 3 9 12 18
        DEPOLARIZE2(0.001) 2 1 16 15 11 10 8 14 3 9 12 18
        TICK
        CX 16 10 11 5 25 19 8 9 17 18 12 13
        DEPOLARIZE2(0.001) 16 10 11 5 25 19 8 9 17 18 12 13
        TICK
        CX 16 8 11 3 25 17 1 9 10 18 5 13
        DEPOLARIZE2(0.001) 16 8 11 3 25 17 1 9 10 18 5 13
        TICK
        H 2 11 16 25
        DEPOLARIZE1(0.001) 2 11 16 25
        TICK
        MR 2 9 11 13 14 16 18 25
        SHIFT_COORDS(0, 0, 1)
        DETECTOR(2, 0, 0) rec[-8] rec[-16]
        DETECTOR(2, 2, 0) rec[-7] rec[-15]
        DETECTOR(4, 2, 0) rec[-6] rec[-14]
        DETECTOR(6, 2, 0) rec[-5] rec[-13]
        DETECTOR(0, 4, 0) rec[-4] rec[-12]
        DETECTOR(2, 4, 0) rec[-3] rec[-11]
        DETECTOR(4, 4, 0) rec[-2] rec[-10]
        DETECTOR(4, 6, 0) rec[-1] rec[-9]
    }
    MX 1 3 5 8 10 12 15 17 19
    DETECTOR(2, 0, 1) rec[-8] rec[-9] rec[-17]
    DETECTOR(2, 4, 1) rec[-2] rec[-3] rec[-5] rec[-6] rec[-12]
    DETECTOR(4, 2, 1) rec[-4] rec[-5] rec[-7] rec[-8] rec[-15]
    DETECTOR(4, 6, 1) rec[-1] rec[-2] rec[-10]
    OBSERVABLE_INCLUDE(0) rec[-3] rec[-6] rec[-9]
''')), 100; kwargs: filepath='/var/folders/tz/6pz51w5s59397cdq3_9qw9cr0000gn/T/tmpz3g99anq/tmpeg__yf6h/sinter_dets.all.b8', obs_out_filepath='/var/folders/tz/6pz51w5s59397cdq3_9qw9cr0000gn/T/tmpz3g99anq/tmpeg__yf6h/sinter_obs.all.b8', format='b8', obs_out_format='b8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../direct_sampling.py", line 64, in <module>
    main()
  File ".../direct_sampling.py", line 26, in main
    samples = sinter.collect(
  File ".../ENV/lib/python3.9/site-packages/sinter/collection.py", line 227, in collect
    for progress in iter_collect(
  File ".../ENV/lib/python3.9/site-packages/sinter/collection.py", line 116, in iter_collect
    sample = manager.wait_for_next_sample()
  File ".../ENV/lib/python3.9/site-packages/sinter/collection_work_manager.py", line 127, in wait_for_next_sample
    raise RuntimeError("Worker failed") from result.error
RuntimeError: Worker failed
```

I'll install stim from source in the meantime but it would be great if the sinter and stim releases could be synced.

**Comment by Strilanc** [comment]
What are the specific versions of stim and sinter that you have installed? You need to have the latest dev version of stim installed to use the latest dev version of sinter. Does it still fail after you run

```
pip install sinter==1.9.dev1654147224 stim==1.9.dev1654147224
```

?
